[package]
name = "affliction"
version = "2.0.0"
authors = ["0v3rl0w <dalcjor@libmail.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]